esphome:
  name: luxtronik
  includes:
    - luxtronik_v1_sensor.h

esp32:
  board: nodemcu-32s
  framework:
    type: arduino


# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: "WLAN67"
  password: "36PqEIsoWCaGmrf9ocVL"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Luxtronik Fallback Hotspot"
    password: "ujB5Yem5CjWc"

captive_portal:

web_server:
  port: 80

mqtt:
  broker: 192.168.178.44
  # Optional variables:
  discovery: true

# Schnittstellen-Parameter: 57600, 8, N, 1
uart:
  baud_rate: 57600
  rx_pin: GPIO3
  tx_pin: GPIO1
  # baud_rate (Required, int): The baud rate of the UART bus.
  # rx_pin (Optional, Pin): The pin to receive data on from the ESP’s perspective.
  # tx_pin (Optional, Pin): The pin to send data to from the ESP’s perspective.
  data_bits: 8
  #data_bits (Optional, int): The number of data bits used on the UART bus. Options: 5 to 8. Defaults to 8.
  #parity (Optional): The parity used on the UART bus. Options: NONE, EVEN, ODD. Defaults to NONE.
  parity: NONE
  #stop_bits (Optional, int): The number of stop bits to send. Options: 1, 2. Defaults to 1.
  stop_bits: 1
  # id (Optional, ID): Manually specify the ID for this UART hub if you need multiple UART hubs
  id: uart_bus
    

    