esphome:
  name: luxtronik_v1
  platform: ESP8266
  board: d1_mini
    
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: True

# Enable logging
logger:
  # disable serial loggin
  baud_rate: 0

web_server:

api:

ota:
  platform: esphome

uart:
  id: uart_bus
  rx_pin: D5
  tx_pin: D6
  baud_rate: 57600
  data_bits: 8
  parity: NONE
  stop_bits: 1
#  debug:
#    direction: BOTH
#    dummy_receiver: false

external_components:
  - source:
      type: git
      url: https://github.com/cbrosius/luxtronik_v1
      ref: main
    components: [ luxtronik_v1_component ]
    refresh: 0s

luxtronik_v1_component:
  id: luxtronik_v1_component_1
  temperatur_vorlauf:
    name: "Temperatur Vorlauf"
    id: temperatur_vorlauf
  temperatur_ruecklauf:
    name: "Temperatur Rücklauf"
    id: temperatur_ruecklauf
  temperatur_ruecklauf_soll:
    name: "Temperatur Rücklauf Soll"
    id: temperatur_ruecklauf_soll
  temperatur_heissgas:
    name: "Temperatur Heissgas"
    id: temperatur_heissgas
  temperatur_aussen:
    name: "Temperatur Aussen"
    id: temperatur_aussen
  temperatur_brauchwasser:
    name: "Temperatur Brauchwasser"
    id: temperatur_brauchwasser
  temperatur_brauchwasser_soll:
    name: "Temperatur Brauchwasser Soll"
    id: temperatur_brauchwasser_soll
  temperatur_waermequelle_eingang:
    name: "Temperatur Wärmequelle Eingang"
    id: temperatur_waermequelle_eingang
  temperatur_kaeltekreis:
    name: "Temperatur Kältekreis"
    id: temperatur_kaeltekreis
  temperatur_mischkreis1_vorlauf:
    name: "Temperatur Mischkreis1 Vorlauf"
    id: temperatur_mischkreis1_vorlauf
  temperatur_mischkreis1_vorlauf_soll:
    name: "Temperatur Mischkreis1 Vorlauf Soll"
    id: temperatur_mischkreis1_vorlauf_soll
  temperatur_raumstation:
    name: "Temperatur Raumstation"
    id: temperatur_raumstation
  eingang_abtau_soledruck_durchfluss:
    name: "Eingang Abtau Soledruck Durchfluss"
    id: eingang_abtau_soledruck_durchfluss
  eingang_sperrzeit_evu:
    name: "Eingang Sperrzeit EVU"
    id: eingang_sperrzeit_evu
  eingang_hochdruckpressostat:
    name: "Eingang Hochdruckpressostat"
    id: eingang_hochdruckpressostat
  eingang_motorschutz:
    name: "Eingang Motorschutz"
    id: eingang_motorschutz
  eingang_niederdruckpressostat:
    name: "Eingang Niederdruckpressostat"
    id: eingang_niederdruckpressostat
  eingang_fremdstromanode:
    name: "Eingang Fremdstromanode"
    id: eingang_fremdstromanode
  # Output sensors
  ausgang_abtauventil:
    name: "Ausgang Abtauventil"
    id: ausgang_abtauventil
  ausgang_brauchwasserpumpe:
    name: "Ausgang Brauchwasserpumpe"
    id: ausgang_brauchwasserpumpe
  ausgang_fussbodenheizungspumpe:
    name: "Ausgang Fußbodenheizungspumpe"
    id: ausgang_fussbodenheizungspumpe
  ausgang_heizungspumpe:
    name: "Ausgang Heizungspumpe"
    id: ausgang_heizungspumpe
  ausgang_mischer_1_auf:
    name: "Ausgang Mischer 1 Auf"
    id: ausgang_mischer_1_auf
  ausgang_mischer_1_zu:
    name: "Ausgang Mischer 1 Zu"
    id: ausgang_mischer_1_zu
  ausgang_ventilator_waermepumpe:
    name: "Ausgang Ventilator Wärmepumpe"
    id: ausgang_ventilator_waermepumpe
  ausgang_ventilator_brunnen:
    name: "Ausgang Ventilator Brunnen"
    id: ausgang_ventilator_brunnen
  ausgang_verdichter_1:
    name: "Ausgang Verdichter 1"
    id: ausgang_verdichter_1
  ausgang_verdichter_2:
    name: "Ausgang Verdichter 2"
    id: ausgang_verdichter_2
  ausgang_zirkulationspumpe:
    name: "Ausgang Zirkulationspumpe"
    id: ausgang_zirkulationspumpe
  ausgang_zweiter_waermeerzeuger:
    name: "Ausgang Zweiter Wärmeerzeuger"
    id: ausgang_zweiter_waermeerzeuger
  ausgang_zweiter_waermeerzeuger_stoerung:
    name: "Ausgang Zweiter Wärmeerzeuger Störung"
    id: ausgang_zweiter_waermeerzeuger_stoerung
    
sensor:
  - platform: uptime
    name: "Uptime Sensor"

button:
  - platform: template
    name: " UART prüfen"
    id: check_uart
    on_press:
      then:
        - uart.write:
            data: "\r\n"
  - platform: template
    name: " Werte manuell abfragen"
    id: ask_for_values
    on_press:
      then:
        - uart.write:
            data: "1100\r\n"
